mobile:
    resource: "@MobileBundle/Resources/config/routing.yml"
    prefix:   /

json:
    resource: "@JsonBundle/Resources/config/routing.yml"
    prefix:   /json

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /app
lib_rate:
    resource: "@LibBundle/Controller/rateController.php"
    type:     annotation

module:
    resource: "@ModuleBundle/Resources/config/routing.yml"
    prefix:   /

logistique:
    resource: "@LogistiqueBundle/Resources/config/routing.yml"
    prefix:   /

lib:
    resource: "@LibBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

classes:
    resource: "@ClassesBundle/Resources/config/routing.yml"
    prefix:   /classe

branches:
    resource: "@BranchesBundle/Resources/config/routing.yml"
    prefix:   /branche

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: '@EventBundle/Controller'
    prefix: /event
    type:  annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

