# app/config/security.yml
security:

    access_denied_url: /login
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:  ROLE_USER
        ROLE_ETUDIANT: ROLE_ETUDIANT
        ROLE_ENSEIGNANT: ROLE_ENSEIGNANT
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_RESPONSABLE: ROLE_RESPONSABLE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: livre_index

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }